dependencies:
- condition: jenkins.enabled
  name: jenkins
  repository: http://chartmuseum.jenkins-x.io
  version: 0.10.38
- alias: expose
  condition: expose.enabled
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.111
- alias: cleanup
  condition: cleanup.enabled
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.111
- condition: chartmuseum.enabled
  name: chartmuseum
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 2.6.1
- condition: nexus.enabled
  name: nexus
  repository: http://chartmuseum.int.caas.ystacks.com:8080
  version: 100.0.0
- name: heapster
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.0.2
- condition: docker-registry.enabled
  name: docker-registry
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.5.0
- alias: gcactivities
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.1094
- alias: gcpods
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.1094
- alias: gcpreviews
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.1094
- alias: controllerbuild
  condition: controllerbuild.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.1094
- alias: controllerrole
  condition: controllerrole.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.1094
- alias: controllerworkflow
  condition: controllerworkflow.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.1094
- alias: controllerteam
  condition: controllerteam.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.1094
- alias: controllercommitstatus
  condition: controllercommitstatus.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.1094
- alias: postinstalljob
  condition: postinstalljob.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.1094
